logging:
  level:
    root[0]: info
    root[1]: debug
    root[2]: warn
spring:
  main:
    banner-mode: off
# h2 ui
# database
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
# ***** When you set h2 in mem you should set ddl-auto: create-drop
# So now you can test and no need initial schema
      ddl-auto: create-drop
# Set url on memory
# ***** Note when you run you have to initial all sql scripts again!!!!
  datasource:
    url: jdbc:h2:mem:test_database
    username: ttknp
    password: